# Generated by Django 5.2.4 on 2025-07-12 07:19

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Dress', 'Dress'), ('Other', 'Other')], max_length=20)),
                ('type', models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Other', 'Other')], max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Worn', 'Worn')], max_length=10)),
                ('tags', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('swapped', 'Swapped')], default='available', max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
