# Generated by Django 5.2.4 on 2025-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='point_value',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('swapped', 'Swapped'), ('redeemed', 'Redeemed')], default='available', max_length=20),
        ),
    ]
